name: 构建页面
on:
  push:  # 指定触发事件
    branches: [main] # 指定触发 action 的分支
  pull_request:
    branches: [main]

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    
    # steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
    # action命令，切换分支获取源码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # 执行依赖安装
    - name: 安装依赖
      run: |
          npm install
        
    # 执行构建步骤
    - name: 构建
      run: |
          npm run build
    # 执行部署
    - name: 部署
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} # 指定密钥，key即密钥名称
        ARGS: '-rltgoDzvO --delete'
        SOURCE: dist # 注意这是npm run build生成的文件，要复制到阿里云静态服务器的文件夹名称
        REMOTE_HOST: ${{ secrets.SERVER_HOST }} # 你的阿里云公网地址
        REMOTE_USER: ${{ secrets.SERVER_USER }}  # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
        TARGET: /root/my-repo # 打包后的 build 文件夹将放在 /root/my-repo
